spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_mvc_security
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/migration.xml
admin:
  password: Syrena69$
  username: albertnadoyan@gmail.com